name: Build and Upload RPK variants

on:
  push:
    branches:
      - next-gen
  pull_request:
    branches:
      - next-gen

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 1

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: "20"

      - name: Install Yarn
        run: npm install -g yarn@1.22.22

      - name: Build two RPK variants (S3/S4)
        run: |
          VARIANT_DESIGN_WIDTH=466 yarn build:variants
          mkdir -p artifacts/s3s4
          mv artifacts/*.rpk artifacts/s3s4/

      - name: Upload two RPK variants (S3/S4)
        uses: actions/upload-artifact@v4.3.6
        with:
          name: RPK variants (Design Width 466) (For S3 S4)
          path: artifacts/s3s4/*.rpk
          if-no-files-found: error
          compression-level: 0

      - name: Build two RPK variants (RW5)
        run: |
          VARIANT_DESIGN_WIDTH=432 yarn build:variants
          mkdir -p artifacts/rw5
          mv artifacts/*.rpk artifacts/rw5/

      - name: Upload two RPK variants (RW5)
        uses: actions/upload-artifact@v4.3.6
        with:
          name: RPK variants (Design Width 432) (RW5)
          path: artifacts/rw5/*.rpk
          if-no-files-found: error
          compression-level: 0
